import {$,app,db,esc,fmtDate,toast,download} from './core.js';

let transactions=[],events=[],contacts=[],members=[],editCashId=null;
const categoryLabels={unclassified:'Da classificare',membership:'Quota associativa',donation:'Donazione',materials:'Materiali',services:'Servizi',event:'Evento',reimbursement:'Rimborso',other:'Altro'};
const euro=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

export async function loadCash(){
 const [tr,er,cr,mr]=await Promise.all([
  db.from('cash_transactions').select('*').order('movement_date',{ascending:false}).order('entry_number',{ascending:false}),
  db.from('events').select('id,name,event_date').order('event_date',{ascending:false}),
  db.from('contacts').select('id,name,organization,active').order('name'),
  db.from('members').select('id,member_number,first_name,last_name,status').order('member_number')
 ]);
 if(tr.error||er.error||cr.error||mr.error){console.error(tr.error||er.error||cr.error||mr.error);toast('Errore caricamento cassa');return}
 transactions=tr.data||[];events=er.data||[];contacts=cr.data||[];members=mr.data||[];fillCashSelects();renderCash();
}

function fillCashSelects(){
 const current=$('cashYearFilter')?.value||'2026';const years=[...new Set(transactions.map(t=>String(t.movement_date).slice(0,4)))].sort((a,b)=>b.localeCompare(a));
 $('cashYearFilter').innerHTML=['<option value="all">Tutti gli anni</option>',...years.map(y=>`<option value="${y}">${y}</option>`)].join('');
 $('cashYearFilter').value=years.includes(current)?current:(years.includes('2026')?'2026':'all');
 $('cashEvent').innerHTML=['<option value="">Nessuno</option>',...events.map(e=>`<option value="${e.id}">${esc(e.name)}${e.event_date?' · '+fmtDate(e.event_date):''}</option>`)].join('');
 $('cashContact').innerHTML=['<option value="">Nessuno</option>',...contacts.map(c=>`<option value="${c.id}">${esc(c.name)}${c.organization?' · '+esc(c.organization):''}${c.active?'':' · archiviato'}</option>`)].join('');
 $('cashMember').innerHTML=['<option value="">Nessuno</option>',...members.map(m=>`<option value="${m.id}">#${String(m.member_number).padStart(3,'0')} · ${esc(m.first_name+' '+m.last_name)}</option>`)].join('');
}
function eventName(id){return events.find(e=>e.id===id)?.name||''}
function contactName(id){return contacts.find(c=>c.id===id)?.name||''}
function memberName(id){const m=members.find(x=>x.id===id);return m?`#${String(m.member_number).padStart(3,'0')} ${m.first_name} ${m.last_name}`:''}
function selectedYearRows(){const y=$('cashYearFilter')?.value||'all';return y==='all'?transactions:transactions.filter(t=>String(t.movement_date).startsWith(y+'-'))}
function filteredRows(){let rows=selectedYearRows();const q=$('cashSearch')?.value?.toLowerCase().trim()||'',tf=$('cashTypeFilter')?.value||'all',cf=$('cashCategoryFilter')?.value||'all';if(tf!=='all')rows=rows.filter(t=>t.movement_type===tf);if(cf!=='all')rows=rows.filter(t=>t.category===cf);if(q)rows=rows.filter(t=>[t.description,t.from_party,t.to_party,t.document_reference,t.notes,eventName(t.event_id),contactName(t.contact_id),memberName(t.member_id),categoryLabels[t.category]].some(v=>(v||'').toLowerCase().includes(q)));return rows.sort((a,b)=>b.movement_date.localeCompare(a.movement_date)||b.entry_number-a.entry_number)}

function totals(rows){const income=rows.filter(t=>t.movement_type==='income').reduce((s,t)=>s+Number(t.amount),0),expense=rows.filter(t=>t.movement_type==='expense').reduce((s,t)=>s+Number(t.amount),0);return{income,expense,balance:income-expense}}
function renderCash(){const base=selectedYearRows(),sum=totals(base);$('cashIncome').textContent=euro(sum.income);$('cashExpense').textContent=euro(sum.expense);$('cashBalance').textContent=euro(sum.balance);$('cashMovements').textContent=base.length;$('cashIncomeCount').textContent=`${base.filter(t=>t.movement_type==='income').length} movimenti`;$('cashExpenseCount').textContent=`${base.filter(t=>t.movement_type==='expense').length} movimenti`;const y=$('cashYearFilter').value;$('cashYearLabel').textContent=y==='all'?'tutto lo storico':`anno ${y}`;renderCouncilors(base);renderMonthly(base);renderLedger()}
function renderCouncilors(rows){const map=new Map();rows.filter(t=>t.movement_type==='expense').forEach(t=>{const m=(t.from_party||'').match(/^Club42 \((.+)\)$/);if(!m)return;const name=m[1];map.set(name,(map.get(name)||0)+Number(t.amount))});const data=[...map.entries()].sort((a,b)=>b[1]-a[1]);$('cashCouncilors').innerHTML=data.length?data.map(([name,value])=>`<div class="cash-councilor-row"><div><b>${esc(name)}</b><small>spese anticipate</small></div><strong>${euro(value)}</strong></div>`).join(''):'<div class="cash-empty">Nessuna spesa anticipata registrata.</div>'}
function renderMonthly(rows){const months=Array.from({length:12},(_,i)=>({m:i+1,income:0,expense:0}));rows.forEach(t=>{const m=Number(String(t.movement_date).slice(5,7));if(!m||!months[m-1])return;months[m-1][t.movement_type]+=Number(t.amount)});const max=Math.max(...months.flatMap(x=>[x.income,x.expense]),1);const labels=['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic'];$('cashMonthlyChart').innerHTML=months.map((x,i)=>`<div class="cash-month" title="${labels[i]} · Entrate ${euro(x.income)} · Uscite ${euro(x.expense)}"><div class="cash-month-bars"><div class="cash-month-bar income" style="height:${Math.max(x.income?5:2,x.income/max*160)}px"></div><div class="cash-month-bar expense" style="height:${Math.max(x.expense?5:2,x.expense/max*160)}px"></div></div><div class="cash-month-label">${labels[i]}</div></div>`).join('')}
function renderLedger(){const rows=filteredRows();$('cashTableBody').innerHTML=rows.length?rows.map(t=>`<tr onclick="openCashTransaction('${t.id}')"><td>${t.entry_number}</td><td>${fmtDate(t.movement_date)}</td><td><span class="cash-type ${t.movement_type}">${t.movement_type==='income'?'Entrata':'Uscita'}</span></td><td><b>${esc(t.description)}</b>${t.document_reference?`<br><span class="muted">${esc(t.document_reference)}</span>`:''}</td><td>${esc(t.from_party||'—')}</td><td>${esc(t.to_party||'—')}</td><td><span class="cash-category ${t.category}">${esc(categoryLabels[t.category]||t.category)}</span></td><td class="num">${euro(t.amount)}</td><td><button class="icon-btn" onclick="event.stopPropagation();openCashTransaction('${t.id}')">✎</button></td></tr>`).join(''):'<tr><td colspan="9" class="empty">Nessun movimento trovato.</td></tr>';
 $('cashMobileList').innerHTML=rows.length?rows.map(t=>`<article class="cash-mobile-card ${t.movement_type}" onclick="openCashTransaction('${t.id}')"><div class="cash-mobile-card-head"><div><span class="cash-type ${t.movement_type}">${t.movement_type==='income'?'Entrata':'Uscita'}</span><h4 style="margin-top:7px">${esc(t.description)}</h4></div><strong>${euro(t.amount)}</strong></div><p>#${t.entry_number} · ${fmtDate(t.movement_date)}<br>${esc(t.from_party||'—')} → ${esc(t.to_party||'—')}</p><div class="cash-mobile-meta"><span>${esc(categoryLabels[t.category]||t.category)}</span>${t.event_id?`<span>${esc(eventName(t.event_id))}</span>`:''}${t.member_id?`<span>${esc(memberName(t.member_id))}</span>`:''}</div></article>`).join(''):'<div class="cash-empty">Nessun movimento trovato.</div>'}

function clearCashForm(){editCashId=null;$('cashForm').reset();$('cashDlgTitle').textContent='Nuovo movimento';$('cashDate').value=localToday();$('cashType').value='expense';$('cashCategory').value='unclassified';$('cashDeleteBtn').style.display='none'}
window.openCashTransaction=id=>{const t=transactions.find(x=>x.id===id);if(!t)return;editCashId=id;$('cashDlgTitle').textContent=`Movimento #${t.entry_number}`;$('cashDate').value=t.movement_date;$('cashType').value=t.movement_type;$('cashAmount').value=t.amount;$('cashCategory').value=t.category||'unclassified';$('cashDescription').value=t.description||'';$('cashFrom').value=t.from_party||'';$('cashTo').value=t.to_party||'';$('cashMethod').value=t.payment_method||'';$('cashDocument').value=t.document_reference||'';$('cashEvent').value=t.event_id||'';$('cashContact').value=t.contact_id||'';$('cashMember').value=t.member_id||'';$('cashNotes').value=t.notes||'';$('cashDeleteBtn').style.display='inline-flex';$('cashDlg').showModal()};
async function saveCash(ev){ev.preventDefault();const row={movement_date:$('cashDate').value,movement_type:$('cashType').value,amount:Number($('cashAmount').value),category:$('cashCategory').value,description:$('cashDescription').value.trim(),from_party:$('cashFrom').value.trim()||null,to_party:$('cashTo').value.trim()||null,payment_method:$('cashMethod').value.trim()||null,document_reference:$('cashDocument').value.trim()||null,event_id:$('cashEvent').value||null,contact_id:$('cashContact').value||null,member_id:$('cashMember').value||null,notes:$('cashNotes').value.trim()||null};let result;if(editCashId)result=await db.from('cash_transactions').update(row).eq('id',editCashId);else result=await db.from('cash_transactions').insert({...row,created_by:app.currentUser.id});if(result.error)return toast(result.error.message);$('cashDlg').close();toast(editCashId?'Movimento aggiornato':'Movimento aggiunto');await loadCash()}
async function deleteCash(){if(!editCashId)return;const t=transactions.find(x=>x.id===editCashId);if(!t||!confirm(`Eliminare definitivamente il movimento #${t.entry_number} “${t.description}”?`))return;const {error}=await db.from('cash_transactions').delete().eq('id',editCashId);if(error)return toast(error.message);$('cashDlg').close();toast('Movimento eliminato');await loadCash()}

function exportRows(){return selectedYearRows().slice().sort((a,b)=>a.movement_date.localeCompare(b.movement_date)||a.entry_number-b.entry_number)}
function exportPeriod(){const y=$('cashYearFilter').value;return y==='all'?'storico':y}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
function exportCsv(){const rows=exportRows(),head=['ID','Data','Tipo','Importo','Descrizione','Da','A','Categoria','Metodo pagamento','Riferimento documento','Evento','Contatto','Socio','Note'];const data=rows.map(t=>[t.entry_number,t.movement_date,t.movement_type==='income'?'Entrata':'Uscita',Number(t.amount).toFixed(2).replace('.',','),t.description,t.from_party,t.to_party,categoryLabels[t.category]||t.category,t.payment_method,t.document_reference,eventName(t.event_id),contactName(t.contact_id),memberName(t.member_id),t.notes]);const csv='\uFEFF'+[head,...data].map(r=>r.map(csvCell).join(';')).join('\n');download(`club42-cassa-${exportPeriod()}.csv`,csv,'text/csv;charset=utf-8')}
function loadScript(src,check){return new Promise((resolve,reject)=>{if(check())return resolve();const found=[...document.scripts].find(s=>s.src===src);if(found){found.addEventListener('load',resolve,{once:true});found.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function exportExcel(){try{await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>!!window.XLSX);const rows=exportRows(),sum=totals(rows),councilors=new Map();rows.filter(t=>t.movement_type==='expense').forEach(t=>{const m=(t.from_party||'').match(/^Club42 \((.+)\)$/);if(m)councilors.set(m[1],(councilors.get(m[1])||0)+Number(t.amount))});const movementData=[['ID','Data','Tipo','Importo','Descrizione','Da','A','Categoria','Metodo pagamento','Riferimento documento','Evento','Contatto','Socio','Note'],...rows.map(t=>[t.entry_number,t.movement_date,t.movement_type==='income'?'Entrata':'Uscita',Number(t.amount),t.description,t.from_party||'',t.to_party||'',categoryLabels[t.category]||t.category,t.payment_method||'',t.document_reference||'',eventName(t.event_id),contactName(t.contact_id),memberName(t.member_id),t.notes||''])];const summary=[['CLUB42 - RENDICONTO CASSA'],['Periodo',exportPeriod()],[],['Entrate',sum.income],['Uscite',sum.expense],['Saldo',sum.balance],['Movimenti',rows.length],[],['Spese anticipate per consigliere'],['Consigliere','Importo'],...[...councilors.entries()].sort((a,b)=>b[1]-a[1])];const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(movementData),rs=XLSX.utils.aoa_to_sheet(summary);ws['!cols']=[{wch:7},{wch:12},{wch:10},{wch:12},{wch:44},{wch:28},{wch:22},{wch:20},{wch:20},{wch:28},{wch:28},{wch:24},{wch:28},{wch:40}];rs['!cols']=[{wch:34},{wch:18}];XLSX.utils.book_append_sheet(wb,ws,'Movimenti');XLSX.utils.book_append_sheet(wb,rs,'Riepilogo');XLSX.writeFile(wb,`club42-cassa-${exportPeriod()}.xlsx`)}catch(e){console.error(e);toast('Impossibile generare Excel')}}
async function exportPdf(){try{await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',()=>!!window.jspdf?.jsPDF);await loadScript('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.2/dist/jspdf.plugin.autotable.min.js',()=>!!window.jspdf?.jsPDF?.API?.autoTable);const rows=exportRows(),sum=totals(rows),{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Club42 - Rendiconto cassa',14,15);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`Periodo: ${exportPeriod()}   |   Entrate: ${euro(sum.income)}   |   Uscite: ${euro(sum.expense)}   |   Saldo: ${euro(sum.balance)}   |   Movimenti: ${rows.length}`,14,22);doc.autoTable({startY:28,head:[['#','Data','Tipo','Importo','Descrizione','Da','A']],body:rows.map(t=>[t.entry_number,new Intl.DateTimeFormat('it-IT').format(new Date(t.movement_date+'T12:00:00')),t.movement_type==='income'?'Entrata':'Uscita',euro(t.amount),t.description,t.from_party||'',t.to_party||'']),styles:{fontSize:7,cellPadding:1.6,overflow:'linebreak'},headStyles:{fillColor:[33,98,119]},columnStyles:{0:{cellWidth:10},1:{cellWidth:21},2:{cellWidth:17},3:{cellWidth:22,halign:'right'},4:{cellWidth:92},5:{cellWidth:52},6:{cellWidth:42}},didDrawPage:data=>{doc.setFontSize(7);doc.setTextColor(120);doc.text(`Club42 · esportato il ${new Intl.DateTimeFormat('it-IT').format(new Date())} · pagina ${doc.internal.getNumberOfPages()}`,14,202)}});doc.save(`club42-cassa-${exportPeriod()}.pdf`)}catch(e){console.error(e);toast('Impossibile generare PDF')}}

export function initCash(){
 $('newCashBtn').onclick=()=>{clearCashForm();$('cashDlg').showModal()};$('cashClose').onclick=()=>$('cashDlg').close();$('cashCancel').onclick=()=>$('cashDlg').close();$('cashForm').onsubmit=saveCash;$('cashDeleteBtn').onclick=deleteCash;
 $('cashSearch').oninput=renderCash;$('cashYearFilter').onchange=renderCash;$('cashTypeFilter').onchange=renderCash;$('cashCategoryFilter').onchange=renderCash;
 $('cashCsvBtn').onclick=exportCsv;$('cashExcelBtn').onclick=exportExcel;$('cashPdfBtn').onclick=exportPdf;
}
