import {$,app,db,esc,fmtDate,toast,download} from './core.js';

let transactions=[],events=[],contacts=[],members=[],users=[],editCashId=null;
let cashChartHeight=Number(sessionStorage.getItem('club42_cash_chart_height'))||(window.innerWidth<=650?105:140);
const categoryLabels={unclassified:'Da classificare',membership:'Quota associativa',donation:'Donazione',materials:'Materiali',services:'Servizi',event:'Evento',reimbursement:'Rimborso',other:'Altro'};
const monthNames=['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];
const monthShort=['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic'];
const euro=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

export async function loadCash(){
 const [tr,er,cr,mr,ur]=await Promise.all([
  db.from('cash_transactions').select('*').order('movement_date',{ascending:false}).order('entry_number',{ascending:false}),
  db.from('events').select('id,name,event_date').order('event_date',{ascending:false}),
  db.from('contacts').select('id,name,organization,active').order('name'),
  db.from('members').select('id,member_number,first_name,last_name,status').order('member_number'),
  db.from('admin_users').select('user_id,display_name,email,role,active,status').order('display_name')
 ]);
 if(tr.error||er.error||cr.error||mr.error||ur.error){console.error(tr.error||er.error||cr.error||mr.error||ur.error);toast('Errore caricamento cassa');return}
 transactions=tr.data||[];events=er.data||[];contacts=cr.data||[];members=mr.data||[];users=ur.data||[];fillCashSelects();renderCash();
}

function fillCashSelects(){
 const currentYear=String(new Date().getFullYear()),previous=$('cashYearFilter')?.value||currentYear;
 const years=[...new Set([currentYear,...transactions.map(t=>String(t.movement_date).slice(0,4))])].sort((a,b)=>b.localeCompare(a));
 $('cashYearFilter').innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('');
 $('cashYearFilter').value=years.includes(previous)?previous:(years.includes(currentYear)?currentYear:years[0]);
 if(!$('cashMonthFrom').options.length){$('cashMonthFrom').innerHTML=monthNames.map((m,i)=>`<option value="${i+1}">Da ${m}</option>`).join('');$('cashMonthFrom').value='1'}
 if(!$('cashMonthTo').options.length){$('cashMonthTo').innerHTML=monthNames.map((m,i)=>`<option value="${i+1}">A ${m}</option>`).join('');$('cashMonthTo').value='12'}
 $('cashEvent').innerHTML=['<option value="">Nessuno</option>',...events.map(e=>`<option value="${e.id}">${esc(e.name)}${e.event_date?' · '+fmtDate(e.event_date):''}</option>`)].join('');
 $('cashContact').innerHTML=['<option value="">Nessuno</option>',...contacts.map(c=>`<option value="${c.id}">${esc(c.name)}${c.organization?' · '+esc(c.organization):''}${c.active?'':' · archiviato'}</option>`)].join('');
 $('cashMember').innerHTML=['<option value="">Nessuno</option>',...members.map(m=>`<option value="${m.id}">#${String(m.member_number).padStart(3,'0')} · ${esc(m.first_name+' '+m.last_name)}</option>`)].join('');
 const eligible=users.filter(u=>u.active&&u.status==='active'&&u.role!=='guest');
 $('cashAssociatedUser').innerHTML=['<option value="">Nessuno</option>',...eligible.map(u=>`<option value="${u.user_id}">${esc(u.display_name||u.email)}</option>`)].join('');
}
function eventName(id){return events.find(e=>e.id===id)?.name||''}
function contactName(id){return contacts.find(c=>c.id===id)?.name||''}
function memberName(id){const m=members.find(x=>x.id===id);return m?`#${String(m.member_number).padStart(3,'0')} ${m.first_name} ${m.last_name}`:''}
function cashUserName(id,snapshot=''){const u=users.find(x=>x.user_id===id);return u?.display_name||u?.email||snapshot||''}
function transactionUserName(t){return cashUserName(t.associated_user_id,t.associated_user_name)}
function selectedYear(){return $('cashYearFilter')?.value||String(new Date().getFullYear())}
function monthRange(){let from=Number($('cashMonthFrom')?.value||1),to=Number($('cashMonthTo')?.value||12);from=Math.min(12,Math.max(1,from));to=Math.min(12,Math.max(1,to));return{from,to}}
function selectedYearRows(){const y=selectedYear();return transactions.filter(t=>String(t.movement_date).startsWith(y+'-'))}
function selectedPeriodRows(){const {from,to}=monthRange();return selectedYearRows().filter(t=>{const m=Number(String(t.movement_date).slice(5,7));return m>=from&&m<=to})}
function periodLabel(){const y=selectedYear(),{from,to}=monthRange();return from===1&&to===12?`anno ${y}`:`${monthNames[from-1]} – ${monthNames[to-1]} ${y}`}
function exportPeriod(){const y=selectedYear(),{from,to}=monthRange();return from===1&&to===12?y:`${y}-${String(from).padStart(2,'0')}_${String(to).padStart(2,'0')}`}
function filteredRows(){let rows=selectedPeriodRows();const q=$('cashSearch')?.value?.toLowerCase().trim()||'',tf=$('cashTypeFilter')?.value||'all',cf=$('cashCategoryFilter')?.value||'all';if(tf!=='all')rows=rows.filter(t=>t.movement_type===tf);if(cf!=='all')rows=rows.filter(t=>t.category===cf);if(q)rows=rows.filter(t=>[t.description,t.from_party,t.to_party,t.document_reference,t.notes,eventName(t.event_id),contactName(t.contact_id),memberName(t.member_id),transactionUserName(t),categoryLabels[t.category]].some(v=>(v||'').toLowerCase().includes(q)));return rows.sort((a,b)=>b.movement_date.localeCompare(a.movement_date)||b.entry_number-a.entry_number)}

function totals(rows){const income=rows.filter(t=>t.movement_type==='income').reduce((s,t)=>s+Number(t.amount),0),expense=rows.filter(t=>t.movement_type==='expense').reduce((s,t)=>s+Number(t.amount),0);return{income,expense,balance:income-expense}}
function advanceSummary(rows){const map=new Map();rows.filter(t=>t.movement_type==='expense'&&!t.user_reimbursed&&(t.associated_user_id||t.associated_user_name)).forEach(t=>{const name=transactionUserName(t)||t.associated_user_name||'Utente storico';const key=t.associated_user_id||`name:${name}`;const current=map.get(key)||{name,value:0};current.value+=Number(t.amount);map.set(key,current)});return[...map.values()].sort((a,b)=>b.value-a.value)}
function renderCash(){const base=selectedPeriodRows(),sum=totals(base);$('cashIncome').textContent=euro(sum.income);$('cashExpense').textContent=euro(sum.expense);$('cashBalance').textContent=euro(sum.balance);$('cashMovements').textContent=base.length;$('cashIncomeCount').textContent=`${base.filter(t=>t.movement_type==='income').length} movimenti`;$('cashExpenseCount').textContent=`${base.filter(t=>t.movement_type==='expense').length} movimenti`;$('cashYearLabel').textContent=periodLabel();renderCouncilors(base);renderMonthly(selectedYearRows());renderLedger()}
function renderCouncilors(rows){const data=advanceSummary(rows);$('cashCouncilors').innerHTML=data.length?data.map(x=>`<div class="cash-councilor-row"><div><b>${esc(x.name)}</b><small>da rimborsare</small></div><strong>${euro(x.value)}</strong></div>`).join(''):'<div class="cash-empty">Nessun rimborso da effettuare agli utenti nel periodo selezionato.</div>'}
function renderMonthly(rows){
 const months=Array.from({length:12},(_,i)=>({m:i+1,income:0,expense:0}));
 rows.forEach(t=>{const m=Number(String(t.movement_date).slice(5,7));if(!m||!months[m-1])return;months[m-1][t.movement_type]+=Number(t.amount)});
 const {from,to}=monthRange(),active=months.filter(x=>x.m>=from&&x.m<=to),max=Math.max(...active.flatMap(x=>[x.income,x.expense]),1),year=selectedYear();
 $('cashChartSubtitle').textContent=`${year} · ${monthNames[from-1]} – ${monthNames[to-1]}`;
 const chart=$('cashMonthlyChart');chart.style.setProperty('--cash-chart-height',`${cashChartHeight}px`);
 chart.innerHTML=months.map((x,i)=>{const enabled=x.m>=from&&x.m<=to;const incomeH=enabled?Math.min(100,Math.max(x.income?5:2,x.income/max*100)):2,expenseH=enabled?Math.min(100,Math.max(x.expense?5:2,x.expense/max*100)):2;return `<div class="cash-month ${enabled?'':'out-range'}"><div class="cash-month-bars"><button type="button" class="cash-month-bar income" style="height:${incomeH}%" ${enabled?`onclick="showCashChartValue(${x.m},'income',${x.income})"`:'disabled'} aria-label="${monthNames[i]} entrate ${euro(x.income)}"></button><button type="button" class="cash-month-bar expense" style="height:${expenseH}%" ${enabled?`onclick="showCashChartValue(${x.m},'expense',${x.expense})"`:'disabled'} aria-label="${monthNames[i]} uscite ${euro(x.expense)}"></button></div><div class="cash-month-label">${monthShort[i]}</div></div>`}).join('');
 $('cashChartSmaller').disabled=cashChartHeight<=80;$('cashChartLarger').disabled=cashChartHeight>=190;
}
window.showCashChartValue=(month,type,amount)=>{document.querySelectorAll('.cash-month-bar.selected').forEach(b=>b.classList.remove('selected'));const bar=[...document.querySelectorAll('.cash-month-bar')].find(b=>b.getAttribute('onclick')?.includes(`(${month},'${type}'`));bar?.classList.add('selected');const label=type==='income'?'Entrate':'Uscite';$('cashChartDetail').innerHTML=`<b>${monthNames[month-1]} ${selectedYear()}</b><span>${label}: <strong class="${type}">${euro(amount)}</strong></span>`}
function resizeCashChart(delta){cashChartHeight=Math.min(190,Math.max(80,cashChartHeight+delta));sessionStorage.setItem('club42_cash_chart_height',String(cashChartHeight));renderMonthly(selectedYearRows())}
function renderLedger(){const rows=filteredRows();$('cashTableBody').innerHTML=rows.length?rows.map(t=>`<tr onclick="openCashTransaction('${t.id}')"><td>${t.entry_number}</td><td>${fmtDate(t.movement_date)}</td><td><span class="cash-type ${t.movement_type}">${t.movement_type==='income'?'Entrata':'Uscita'}</span></td><td><b>${esc(t.description)}</b>${t.document_reference?`<br><span class="muted">${esc(t.document_reference)}</span>`:''}</td><td>${esc(t.from_party||'—')}</td><td>${esc(t.to_party||'—')}</td><td>${esc(transactionUserName(t)||'—')}${t.movement_type==='expense'&&transactionUserName(t)?`<br><span class="cash-reimbursement-badge ${t.user_reimbursed?'done':'due'}">${t.user_reimbursed?'Rimborsato':'Da rimborsare'}</span>`:''}</td><td><span class="cash-category ${t.category}">${esc(categoryLabels[t.category]||t.category)}</span></td><td class="num">${euro(t.amount)}</td><td><button class="icon-btn" onclick="event.stopPropagation();openCashTransaction('${t.id}')">✎</button></td></tr>`).join(''):'<tr><td colspan="10" class="empty">Nessun movimento trovato.</td></tr>';
 $('cashMobileList').innerHTML=rows.length?rows.map(t=>`<article class="cash-mobile-card ${t.movement_type}" onclick="openCashTransaction('${t.id}')"><div class="cash-mobile-card-head"><div><span class="cash-type ${t.movement_type}">${t.movement_type==='income'?'Entrata':'Uscita'}</span><h4 style="margin-top:7px">${esc(t.description)}</h4></div><strong>${euro(t.amount)}</strong></div><p>#${t.entry_number} · ${fmtDate(t.movement_date)}<br>${esc(t.from_party||'—')} → ${esc(t.to_party||'—')}</p><div class="cash-mobile-meta"><span>${esc(categoryLabels[t.category]||t.category)}</span>${transactionUserName(t)?`<span>👤 ${esc(transactionUserName(t))}</span>`:''}${t.movement_type==='expense'&&transactionUserName(t)?`<span class="cash-reimbursement-badge ${t.user_reimbursed?'done':'due'}">${t.user_reimbursed?'Rimborsato':'Da rimborsare'}</span>`:''}${t.event_id?`<span>${esc(eventName(t.event_id))}</span>`:''}${t.member_id?`<span>${esc(memberName(t.member_id))}</span>`:''}</div></article>`).join(''):'<div class="cash-empty">Nessun movimento trovato.</div>'}

function syncReimbursedControl(resetWhenUnavailable=true){const wrap=$('cashReimbursedWrap'),input=$('cashUserReimbursed');if(!wrap||!input)return;const eligible=$('cashType')?.value==='expense'&&!!$('cashAssociatedUser')?.value;wrap.hidden=!eligible;input.disabled=!eligible;if(!eligible&&resetWhenUnavailable)input.checked=false}
function openCashDialog(){const dlg=$('cashDlg');dlg.showModal();requestAnimationFrame(()=>{$('cashForm').scrollTop=0})}
function clearCashForm(){editCashId=null;$('cashForm').reset();$('cashDlgTitle').textContent='Nuovo movimento';$('cashDate').value=localToday();$('cashType').value='expense';$('cashCategory').value='unclassified';$('cashAssociatedUser').value='';$('cashUserReimbursed').checked=false;syncReimbursedControl();$('cashDeleteBtn').style.display='none'}
function setAssociatedUserValue(t){const select=$('cashAssociatedUser'),id=t?.associated_user_id||'';if(id&&![...select.options].some(o=>o.value===id)){const option=document.createElement('option');option.value=id;option.textContent=`${t.associated_user_name||'Utente storico'} · non selezionabile`;option.disabled=true;select.appendChild(option)}select.value=id}
window.openCashTransaction=id=>{const t=transactions.find(x=>x.id===id);if(!t)return;editCashId=id;$('cashDlgTitle').textContent=`Movimento #${t.entry_number}`;$('cashDate').value=t.movement_date;$('cashType').value=t.movement_type;$('cashAmount').value=t.amount;$('cashCategory').value=t.category||'unclassified';$('cashDescription').value=t.description||'';$('cashFrom').value=t.from_party||'';$('cashTo').value=t.to_party||'';$('cashMethod').value=t.payment_method||'';$('cashDocument').value=t.document_reference||'';$('cashEvent').value=t.event_id||'';$('cashContact').value=t.contact_id||'';$('cashMember').value=t.member_id||'';setAssociatedUserValue(t);$('cashUserReimbursed').checked=!!t.user_reimbursed;syncReimbursedControl(false);$('cashNotes').value=t.notes||'';$('cashDeleteBtn').style.display='inline-flex';openCashDialog()};
async function saveCash(ev){ev.preventDefault();const associatedId=$('cashAssociatedUser').value||null,current=editCashId?transactions.find(x=>x.id===editCashId):null,selectedUser=associatedId?users.find(u=>u.user_id===associatedId):null;const row={movement_date:$('cashDate').value,movement_type:$('cashType').value,amount:Number($('cashAmount').value),category:$('cashCategory').value,description:$('cashDescription').value.trim(),from_party:$('cashFrom').value.trim()||null,to_party:$('cashTo').value.trim()||null,associated_user_id:associatedId,associated_user_name:associatedId?(selectedUser?.display_name||selectedUser?.email||current?.associated_user_name||null):null,user_reimbursed:$('cashType').value==='expense'&&!!associatedId&&!!$('cashUserReimbursed')?.checked,payment_method:$('cashMethod').value.trim()||null,document_reference:$('cashDocument').value.trim()||null,event_id:$('cashEvent').value||null,contact_id:$('cashContact').value||null,member_id:$('cashMember').value||null,notes:$('cashNotes').value.trim()||null};let result;if(editCashId)result=await db.from('cash_transactions').update(row).eq('id',editCashId);else result=await db.from('cash_transactions').insert({...row,created_by:app.currentUser.id});if(result.error)return toast(result.error.message);$('cashDlg').close();toast(editCashId?'Movimento aggiornato':'Movimento aggiunto');await loadCash()}
async function deleteCash(){if(!editCashId)return;const t=transactions.find(x=>x.id===editCashId);if(!t||!confirm(`Eliminare definitivamente il movimento #${t.entry_number} “${t.description}”?`))return;const {error}=await db.from('cash_transactions').delete().eq('id',editCashId);if(error)return toast(error.message);$('cashDlg').close();toast('Movimento eliminato');await loadCash()}

function exportRows(){return selectedPeriodRows().slice().sort((a,b)=>a.movement_date.localeCompare(b.movement_date)||a.entry_number-b.entry_number)}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
function exportCsv(){const rows=exportRows(),head=['ID','Data','Tipo','Importo','Descrizione','Da','A','Utente Club42','Rimborso utente','Categoria','Metodo pagamento','Riferimento documento','Evento','Contatto','Socio','Note'];const data=rows.map(t=>[t.entry_number,t.movement_date,t.movement_type==='income'?'Entrata':'Uscita',Number(t.amount).toFixed(2).replace('.',','),t.description,t.from_party,t.to_party,transactionUserName(t),t.movement_type==='expense'&&transactionUserName(t)?(t.user_reimbursed?'Rimborsato':'Da rimborsare'):'',categoryLabels[t.category]||t.category,t.payment_method,t.document_reference,eventName(t.event_id),contactName(t.contact_id),memberName(t.member_id),t.notes]);const csv='\uFEFF'+[head,...data].map(r=>r.map(csvCell).join(';')).join('\n');download(`club42-cassa-${exportPeriod()}.csv`,csv,'text/csv;charset=utf-8')}
function loadScript(src,check){return new Promise((resolve,reject)=>{if(check())return resolve();const found=[...document.scripts].find(s=>s.src===src);if(found){found.addEventListener('load',resolve,{once:true});found.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function exportExcel(){try{await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>!!window.XLSX);const rows=exportRows(),sum=totals(rows),advances=advanceSummary(rows);const movementData=[['ID','Data','Tipo','Importo','Descrizione','Da','A','Utente Club42','Rimborso utente','Categoria','Metodo pagamento','Riferimento documento','Evento','Contatto','Socio','Note'],...rows.map(t=>[t.entry_number,t.movement_date,t.movement_type==='income'?'Entrata':'Uscita',Number(t.amount),t.description,t.from_party||'',t.to_party||'',transactionUserName(t),categoryLabels[t.category]||t.category,t.payment_method||'',t.document_reference||'',eventName(t.event_id),contactName(t.contact_id),memberName(t.member_id),t.notes||''])];const summary=[['CLUB42 - RENDICONTO CASSA'],['Periodo',periodLabel()],[],['Entrate',sum.income],['Uscite',sum.expense],['Saldo',sum.balance],['Movimenti',rows.length],[],['Spese anticipate per utente'],['Utente','Importo'],...advances.map(x=>[x.name,x.value])];const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(movementData),rs=XLSX.utils.aoa_to_sheet(summary);ws['!cols']=[{wch:7},{wch:12},{wch:10},{wch:12},{wch:44},{wch:28},{wch:22},{wch:30},{wch:20},{wch:20},{wch:28},{wch:28},{wch:24},{wch:28},{wch:40}];rs['!cols']=[{wch:38},{wch:18}];XLSX.utils.book_append_sheet(wb,ws,'Movimenti');XLSX.utils.book_append_sheet(wb,rs,'Riepilogo');XLSX.writeFile(wb,`club42-cassa-${exportPeriod()}.xlsx`)}catch(e){console.error(e);toast('Impossibile generare Excel')}}
async function exportPdf(){try{await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',()=>!!window.jspdf?.jsPDF);await loadScript('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.2/dist/jspdf.plugin.autotable.min.js',()=>!!window.jspdf?.jsPDF?.API?.autoTable);const rows=exportRows(),sum=totals(rows),{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Club42 - Rendiconto cassa',14,15);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`Periodo: ${periodLabel()}   |   Entrate: ${euro(sum.income)}   |   Uscite: ${euro(sum.expense)}   |   Saldo: ${euro(sum.balance)}   |   Movimenti: ${rows.length}`,14,22);doc.autoTable({startY:28,head:[['#','Data','Tipo','Importo','Descrizione','Da','A','Utente Club42']],body:rows.map(t=>[t.entry_number,new Intl.DateTimeFormat('it-IT').format(new Date(t.movement_date+'T12:00:00')),t.movement_type==='income'?'Entrata':'Uscita',euro(t.amount),t.description,t.from_party||'',t.to_party||'',transactionUserName(t)]),styles:{fontSize:6.6,cellPadding:1.5,overflow:'linebreak'},headStyles:{fillColor:[33,98,119]},columnStyles:{0:{cellWidth:9},1:{cellWidth:20},2:{cellWidth:16},3:{cellWidth:21,halign:'right'},4:{cellWidth:70},5:{cellWidth:39},6:{cellWidth:35},7:{cellWidth:46}},didDrawPage:data=>{doc.setFontSize(7);doc.setTextColor(120);doc.text(`Club42 · esportato il ${new Intl.DateTimeFormat('it-IT').format(new Date())} · pagina ${doc.internal.getNumberOfPages()}`,14,202)}});doc.save(`club42-cassa-${exportPeriod()}.pdf`)}catch(e){console.error(e);toast('Impossibile generare PDF')}}

export function initCash(){
 $('newCashBtn').onclick=()=>{clearCashForm();openCashDialog()};$('cashClose').onclick=()=>$('cashDlg').close();$('cashCancel').onclick=()=>$('cashDlg').close();$('cashForm').onsubmit=saveCash;$('cashDeleteBtn').onclick=deleteCash;$('cashType').onchange=()=>syncReimbursedControl();$('cashAssociatedUser').onchange=()=>syncReimbursedControl();
 $('cashSearch').oninput=renderCash;$('cashYearFilter').onchange=()=>{$('cashChartDetail').textContent='Seleziona una barra del grafico.';renderCash()};$('cashMonthFrom').onchange=()=>{if(Number($('cashMonthFrom').value)>Number($('cashMonthTo').value))$('cashMonthTo').value=$('cashMonthFrom').value;$('cashChartDetail').textContent='Seleziona una barra del grafico.';renderCash()};$('cashMonthTo').onchange=()=>{if(Number($('cashMonthTo').value)<Number($('cashMonthFrom').value))$('cashMonthFrom').value=$('cashMonthTo').value;$('cashChartDetail').textContent='Seleziona una barra del grafico.';renderCash()};$('cashTypeFilter').onchange=renderCash;$('cashCategoryFilter').onchange=renderCash;
 $('cashChartSmaller').onclick=()=>resizeCashChart(-25);$('cashChartLarger').onclick=()=>resizeCashChart(25);
 $('cashCsvBtn').onclick=exportCsv;$('cashExcelBtn').onclick=exportExcel;$('cashPdfBtn').onclick=exportPdf;
}
