export function buildMembersUi(){
  if(!document.querySelector('link[href^="members.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='members.css?v=20260918-cycle1';document.head.appendChild(l)}
  const nav=document.querySelector('.nav-item[data-view="members"]');if(nav){const b=nav.querySelector('.nav-badge');if(b)b.remove()}
  const view=document.getElementById('view-members');if(view)view.innerHTML=`<div class="members-shell">
    <section class="card members-hero"><div class="members-hero-top"><div><div class="hero-eyebrow">Club42 · Registro ufficiale</div><h2>Registro soci</h2><p>Anagrafica, tessere, rinnovi, quote annuali e dati mancanti in un unico archivio condiviso.</p></div><div class="members-actions"><button class="btn primary" id="newMemberBtn">＋ Nuovo socio</button></div></div></section>
    <div class="members-summary"><div class="card"><span>Soci totali</span><b id="memTotal">0</b></div><div class="card"><span>Attivi</span><b id="memActive">0</b></div><div class="card"><span>Da rinnovare</span><b id="memRenew">0</b></div><div class="card"><span>Dati incompleti</span><b id="memMissing">0</b></div></div>

    <section class="card renewal-panel"><div class="renewal-copy"><div class="panel-kicker">Rinnovi</div><h3>Scadenza tessera anno associativo corrente</h3><p>L'annualità Club42 va dal <b>1° settembre</b> al <b>31 agosto</b>. Dal 1° settembre successivo, chi era già socio e non risulta rinnovato per la nuova annualità passa automaticamente a <b>Da rinnovare</b>.</p></div><div class="renewal-expiry-box"><span>Annualità <b id="renewalCycleLabel">—</b></span><strong id="renewalExpiryDate">—</strong><small>Si aggiorna automaticamente ogni 1° settembre.</small></div></section>

    <section class="card members-panel"><div class="section-head"><div><h3>Elenco soci</h3><p>Ordinato per numero tessera · annualità <span id="memYearLabel"></span></p></div><div class="export-group"><button class="btn" id="exportMembersPdf">PDF</button><button class="btn" id="exportMembersCsv">CSV</button><button class="btn" id="exportMembersXlsx">Excel</button></div></div>
    <div class="members-toolbar"><input id="memberSearch" placeholder="🔎 Cerca nome, email, codice fiscale…"><select id="memberStatusFilter"><option value="all">Tutti gli stati</option><option value="active">Attivi</option><option value="suspended">Sospesi</option><option value="resigned">Dimessi</option><option value="expired">Scaduti</option></select><select id="memberFeeFilter"><option value="all">Tutti i rinnovi</option><option value="paid">Quota pagata</option><option value="due">Da rinnovare</option><option value="unknown">Da verificare</option><option value="waived">Esente</option></select><select id="memberDataFilter"><option value="all">Tutti i dati</option><option value="incomplete">Dati incompleti</option><option value="complete">Dati completi</option></select></div>
    <div class="member-status-help"><b>Stati socio:</b> <span><strong>Attivo</strong> = socio regolare</span><span><strong>Sospeso</strong> = rapporto temporaneamente sospeso ma storico conservato</span><span><strong>Dimesso</strong> = uscita volontaria, mantenuta nello storico</span><span><strong>Scaduto</strong> = non più valido e cancellabile in massa</span><span><strong>Da rinnovare</strong> è invece uno stato della quota, non del socio.</span></div>
    <div class="members-danger-row"><button class="btn danger" id="deleteExpiredMembers">Elimina tutti gli scaduti</button></div>
    <div class="members-table-wrap"><table class="members-table"><thead><tr><th>#</th><th>Socio</th><th>Codice fiscale</th><th>Contatti</th><th>Iscrizione</th><th>Stato</th><th>Rinnovo</th><th>Firma</th><th></th></tr></thead><tbody id="membersRows"></tbody></table></div><div class="member-mobile" id="membersCards"></div></section>
  </div>`;
  if(!document.getElementById('memberDlg'))document.body.insertAdjacentHTML('beforeend',`<dialog id="memberDlg" class="social-dialog-wide"><form class="modal" id="memberForm"><div class="modal-head"><h3 id="memberDlgTitle">Nuovo socio</h3><button type="button" class="close" id="memberClose">×</button></div><div class="form-grid">
  <div class="field"><label>Nome *</label><input id="mFirst" required></div><div class="field"><label>Cognome *</label><input id="mLast" required></div><div class="field"><label>Numero socio</label><input id="mNumber" type="number" min="1" placeholder="Automatico"></div><div class="field"><label>Data iscrizione *</label><input id="mJoin" type="date" required></div><div class="field"><label>Codice fiscale</label><input id="mTax"></div><div class="field"><label>Email</label><input id="mEmail" type="email"></div><div class="field"><label>Telefono</label><input id="mPhone"></div><div class="field"><label>Stato socio</label><select id="mStatus"><option value="active">Attivo</option><option value="suspended">Sospeso</option><option value="resigned">Dimesso</option><option value="expired">Scaduto</option></select></div><div class="field"><label>Firma ricevuta</label><select id="mSignature"><option value="false">No</option><option value="true">Sì</option></select></div><div class="field full"><label>Note</label><textarea id="mNotes" rows="3"></textarea></div>
  <div class="member-section-title">Quota / rinnovo <span id="feeYearTitle"></span></div><div class="field"><label>Importo</label><input id="mfAmount" type="number" min="0" step="0.01" value="15"></div><div class="field"><label>Stato rinnovo</label><select id="mfStatus"><option value="unknown">Da verificare</option><option value="due">Da rinnovare</option><option value="paid">Pagata</option><option value="waived">Esente</option></select></div><div class="field"><label>Data pagamento</label><input id="mfPaidAt" type="date"></div><div class="field"><label>Metodo</label><input id="mfMethod" placeholder="Contanti, bonifico…"></div><div class="field"><label>N. ricevuta</label><input id="mfReceipt"></div><div class="field"><label>Note quota</label><input id="mfNotes"></div>
  </div><div class="modal-actions"><button type="button" class="btn danger" id="memberDeleteBtn" style="display:none;margin-right:auto">Elimina</button><button type="button" class="btn" id="memberCancel">Annulla</button><button class="btn primary">Salva</button></div></form></dialog>`)
}
