import {$,app,db,esc,fmtDate,toast} from './core.js';

let projects=[],tasks=[],updates=[],users=[],voteUsers=[],events=[],projectVotes=[],editProjectId=null,editTaskId=null,activeTab='radar';
const statusLabels={idea:'Idea',evaluation:'Valutazione',planning:'Pianificazione',confirmed:'Confermato',production:'Produzione',completed:'Completato',archived:'Archiviato',cancelled:'Annullato'};
const priorityLabels={urgent:'Urgente',high:'Alta',medium:'Media',low:'Bassa'};
const categoryLabels={event:'Evento',partnership:'Collaborazione',internal:'Interno',social:'Social',other:'Altro'};
const taskStatusLabels={todo:'Da fare',doing:'In corso',blocked:'Bloccato',done:'Fatto'};

function ownerName(id){const u=users.find(x=>x.user_id===id);return u?.display_name||u?.email||'—'}
function projectTasks(id){return tasks.filter(t=>t.project_id===id)}
function projectUpdates(id){return updates.filter(u=>u.project_id===id).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))}
function isClosed(p){return ['completed','archived','cancelled'].includes(p.status)}
function today(){return new Date().toISOString().slice(0,10)}
function attentionScore(p){let s=0;const ts=projectTasks(p.id);if(ts.some(t=>t.status==='blocked'))s+=4;if(p.next_action_due&&p.next_action_due<today())s+=3;if(p.target_date&&p.target_date<today()&&!isClosed(p))s+=3;if(p.priority==='urgent')s+=2;if(!p.next_action&&!isClosed(p))s+=1;return s}
function progress(p){const ts=projectTasks(p.id);if(ts.length)return Math.round(ts.filter(t=>t.status==='done').length/ts.length*100);const map={idea:5,evaluation:15,planning:35,confirmed:50,production:75,completed:100,archived:100,cancelled:0};return map[p.status]??0}
function money(v){return v==null||v===''?'—':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v))}
function canVoteProject(){return ['admin','staff','treasurer'].includes(app.currentProfile?.role||'')}
function projectVotesFor(id){return projectVotes.filter(v=>v.project_id===id)}
function voteUserName(id){const u=voteUsers.find(x=>x.user_id===id)||users.find(x=>x.user_id===id);return u?.display_name||u?.email||'Utente non disponibile'}
function projectVoteStats(id){const vv=projectVotesFor(id),me=vv.find(v=>v.voter_id===app.currentUser?.id);return{positive:vv.filter(v=>Number(v.vote)===1).length,negative:vv.filter(v=>Number(v.vote)===-1).length,mine:Number(me?.vote||0)}}
function projectVoteControls(id,compact=false){const s=projectVoteStats(id);return `<div class="club-vote-strip${compact?' compact':''}" onclick="event.stopPropagation()"><button type="button" class="club-vote-btn positive ${s.mine===1?'active':''}" aria-label="Voto positivo" aria-pressed="${s.mine===1}" onclick="event.stopPropagation();setProjectVote('${id}',1)">👍 <b>${s.positive}</b></button><button type="button" class="club-vote-btn negative ${s.mine===-1?'active':''}" aria-label="Voto negativo" aria-pressed="${s.mine===-1}" onclick="event.stopPropagation();setProjectVote('${id}',-1)">👎 <b>${s.negative}</b></button><button type="button" class="club-vote-details" onclick="event.stopPropagation();openProjectVotes('${id}')">Chi ha votato</button></div>`}
function ensureProjectVotesDialog(){if($('projectVotesDlg'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="projectVotesDlg" class="club-votes-dialog"><div class="modal club-votes-modal"><div class="modal-head"><div><div class="project-modal-kicker">Valutazione trasparente</div><h3 id="projectVotesTitle">Voti progetto</h3></div><button type="button" class="close" id="projectVotesClose">×</button></div><div id="projectVotesBody" class="club-votes-body"></div><div class="modal-actions"><button type="button" class="btn" id="projectVotesDone">Chiudi</button></div></div></dialog>`);$('projectVotesClose').onclick=()=>$('projectVotesDlg').close();$('projectVotesDone').onclick=()=>$('projectVotesDlg').close()}
function renderProjectVotePanel(id){const root=$('projectVotePanel');if(!root)return;if(!id){root.innerHTML='<div class="project-empty">Salva prima il progetto per raccogliere voti.</div>';return}root.innerHTML=projectVoteControls(id)}
window.openProjectVotes=id=>{const p=projects.find(x=>x.id===id);if(!p)return;ensureProjectVotesDialog();const vv=projectVotesFor(id).slice().sort((a,b)=>voteUserName(a.voter_id).localeCompare(voteUserName(b.voter_id),'it'));const pos=vv.filter(v=>Number(v.vote)===1),neg=vv.filter(v=>Number(v.vote)===-1);$('projectVotesTitle').textContent=p.title;const list=(rows,empty)=>rows.length?rows.map(v=>`<div class="club-voter-row"><span>${esc(voteUserName(v.voter_id))}</span><b>${Number(v.vote)===1?'👍 Favorevole':'👎 Contrario'}</b></div>`).join(''):`<div class="club-votes-empty">${empty}</div>`;$('projectVotesBody').innerHTML=`<section><div class="club-votes-section-title"><span>👍 Favorevoli</span><b>${pos.length}</b></div>${list(pos,'Nessun voto positivo.')}</section><section><div class="club-votes-section-title"><span>👎 Contrari</span><b>${neg.length}</b></div>${list(neg,'Nessun voto negativo.')}</section>`;$('projectVotesDlg').showModal()}
window.setProjectVote=async(id,vote)=>{if(!canVoteProject())return toast('Il tuo profilo non può votare i progetti.');const current=projectVotes.find(v=>v.project_id===id&&v.voter_id===app.currentUser?.id);let result;if(current&&Number(current.vote)===Number(vote))result=await db.from('project_votes').delete().eq('project_id',id).eq('voter_id',app.currentUser.id);else result=await db.from('project_votes').upsert({project_id:id,voter_id:app.currentUser.id,vote:Number(vote),updated_at:new Date().toISOString()},{onConflict:'project_id,voter_id'});if(result.error)return toast(result.error.message);await loadProjects();if(editProjectId===id)renderProjectVotePanel(id);toast(current&&Number(current.vote)===Number(vote)?'Voto rimosso':'Voto registrato')}


export async function loadProjects(){
 const [pr,tr,ur,ar,vr,avr,er]=await Promise.all([
  db.from('projects').select('*').order('updated_at',{ascending:false}),
  db.from('project_tasks').select('*').order('sort_order').order('created_at'),
  db.from('project_updates').select('*').order('created_at',{ascending:false}),
  db.from('admin_users').select('user_id,display_name,email,role,active,status').eq('active',true),
  db.from('project_votes').select('*'),
  db.from('admin_users').select('user_id,display_name,email,role,active,status'),
  db.from('events').select('id,name,event_date').order('event_date',{ascending:false})
 ]);
 if(pr.error||tr.error||ur.error||ar.error||vr.error||avr.error||er.error){console.error(pr.error||tr.error||ur.error||ar.error||vr.error||avr.error||er.error);toast('Errore caricamento progetti');return}
 projects=pr.data||[];tasks=tr.data||[];updates=ur.data||[];users=ar.data||[];projectVotes=vr.data||[];voteUsers=avr.data||[];events=er.data||[];fillSelects();renderProjects();
}

function fillSelects(){const owners=['<option value="">Nessuno</option>',...users.map(u=>`<option value="${u.user_id}">${esc(u.display_name||u.email)}</option>`)].join('');$('prOwner').innerHTML=owners;$('ptOwner').innerHTML=owners;$('prEvent').innerHTML=['<option value="">Nessuno</option>',...events.map(e=>`<option value="${e.id}">${esc(e.name)}${e.event_date?' · '+fmtDate(e.event_date):''}</option>`)].join('')}

function setTab(name){activeTab=name;document.querySelectorAll('.projects-tab').forEach(b=>b.classList.toggle('active',b.dataset.ptab===name));document.querySelectorAll('.project-tab-panel').forEach(p=>p.classList.toggle('active',p.id==='project-panel-'+name));if(name==='archive')renderArchive()}

function renderProjects(){
 const active=projects.filter(p=>!isClosed(p)&&p.status!=='idea').length,att=projects.filter(p=>!isClosed(p)&&attentionScore(p)>0).length,ideas=projects.filter(p=>p.status==='idea'||p.status==='evaluation').length,done=projects.filter(p=>p.status==='completed').length;
 $('prActive').textContent=active;$('prAttention').textContent=att;$('prIdeas').textContent=ideas;$('prCompleted').textContent=done;
 renderRadar();renderBoard();renderArchive();
}
function renderRadar(){
 const attention=projects.filter(p=>!isClosed(p)&&attentionScore(p)>0).sort((a,b)=>attentionScore(b)-attentionScore(a)).slice(0,7);
 $('projectAttentionList').innerHTML=attention.length?attention.map(p=>radarRow(p,'⚠')).join(''):'<div class="project-empty">Nessun progetto richiede attenzione. Ottimo.</div>';
 const upcoming=projects.filter(p=>!isClosed(p)&&p.target_date).sort((a,b)=>a.target_date.localeCompare(b.target_date)).slice(0,7);
 $('projectUpcomingList').innerHTML=upcoming.length?upcoming.map(p=>radarRow(p,'◎')).join(''):'<div class="project-empty">Nessun traguardo pianificato.</div>';
 const active=projects.filter(p=>!isClosed(p)).sort((a,b)=>(attentionScore(b)-attentionScore(a))||(new Date(b.updated_at)-new Date(a.updated_at)));
 $('projectPortfolioGrid').innerHTML=active.length?active.map(projectCard).join(''):'<div class="project-empty">Nessun progetto attivo. Crea la prossima idea Club42.</div>';
}
function radarRow(p,icon){const blocked=projectTasks(p.id).some(t=>t.status==='blocked');const cls=attentionScore(p)>2?' project-attention':'';return `<article class="project-radar-item${cls}" onclick="openProject('${p.id}')"><div class="project-radar-icon">${icon}</div><div><h4>${esc(p.title)}</h4><p>${blocked?'Task bloccato · ':''}${esc(p.next_action||p.summary||statusLabels[p.status])}</p></div><div class="project-radar-date">${p.next_action_due?fmtDate(p.next_action_due):p.target_date?fmtDate(p.target_date):''}</div></article>`}
function projectCard(p){const ts=projectTasks(p.id),done=ts.filter(t=>t.status==='done').length;return `<article class="project-card" onclick="openProject('${p.id}')"><div class="project-card-top"><span class="project-badge">${statusLabels[p.status]}</span><span class="project-badge project-priority-${p.priority}">${priorityLabels[p.priority]}</span></div><h4>${esc(p.title)}</h4><p>${esc(p.summary||'Nessuna descrizione')}</p><div class="project-card-meta"><span>${categoryLabels[p.category]}</span>${p.owner_id?`<span>${esc(ownerName(p.owner_id))}</span>`:''}${p.target_date?`<span>◎ ${fmtDate(p.target_date)}</span>`:''}</div><div class="project-progress"><i style="width:${progress(p)}%"></i></div><p style="margin-top:6px">${ts.length?`${done}/${ts.length} task completati`:`Avanzamento ${progress(p)}%`}</p>${projectVoteControls(p.id,true)}</article>`}
function renderBoard(){const cols=[['idea','Idee'],['evaluation','Valutazione'],['planning','Pianificazione'],['confirmed','Confermati'],['production','Produzione'],['completed','Completati']];$('projectBoard').innerHTML=cols.map(([st,label])=>{const pp=projects.filter(p=>p.status===st);return `<section class="project-column"><div class="project-column-head"><b>${label}</b><span>${pp.length}</span></div><div class="project-column-body">${pp.length?pp.map(p=>`<article class="project-board-card" onclick="openProject('${p.id}')"><div class="project-card-top"><span class="project-badge project-priority-${p.priority}">${priorityLabels[p.priority]}</span><span class="muted">${p.target_date?fmtDate(p.target_date):''}</span></div><h4>${esc(p.title)}</h4><p>${esc(p.next_action||p.summary||'')}</p><div class="project-progress"><i style="width:${progress(p)}%"></i></div></article>`).join(''):'<div class="project-empty">Vuoto</div>'}</div></section>`}).join('')}
function renderArchive(){const q=$('projectSearch')?.value?.toLowerCase().trim()||'',sf=$('projectStatusFilter')?.value||'all',pf=$('projectPriorityFilter')?.value||'all';let rows=projects.filter(p=>sf==='all'||p.status===sf).filter(p=>pf==='all'||p.priority===pf);if(q)rows=rows.filter(p=>[p.title,p.summary,p.partner,p.location,p.objective,p.audience,ownerName(p.owner_id)].some(v=>(v||'').toLowerCase().includes(q)));$('projectArchiveList').innerHTML=rows.length?rows.map(p=>`<article class="project-archive-row" onclick="openProject('${p.id}')"><div><h4>${esc(p.title)}</h4><p>${esc(p.summary||'')}</p></div><div><span class="project-badge">${statusLabels[p.status]}</span></div><div><span class="project-badge project-priority-${p.priority}">${priorityLabels[p.priority]}</span></div><div>${p.owner_id?esc(ownerName(p.owner_id)):'—'}</div><div>${p.target_date?fmtDate(p.target_date):'—'}</div></article>`).join(''):'<div class="project-empty">Nessun progetto trovato.</div>'}

function clearProjectForm(){editProjectId=null;$('projectForm').reset();$('projectDlgTitle').textContent='Nuovo progetto';$('prStatus').value='idea';$('prPriority').value='medium';$('prCategory').value='event';$('projectDeleteBtn').style.display='none';$('projectTasksList').innerHTML='<div class="project-empty">Salva prima il progetto per aggiungere task.</div>';$('projectUpdatesList').innerHTML='<div class="project-empty">Salva prima il progetto per aggiungere aggiornamenti.</div>'};renderProjectVotePanel(null)
window.openProject=id=>{const p=projects.find(x=>x.id===id);if(!p)return;editProjectId=id;$('projectDlgTitle').textContent=p.title;$('prTitle').value=p.title;$('prSummary').value=p.summary||'';$('prStatus').value=p.status;$('prPriority').value=p.priority;$('prCategory').value=p.category;$('prOwner').value=p.owner_id||'';$('prStart').value=p.start_date||'';$('prTarget').value=p.target_date||'';$('prLocation').value=p.location||'';$('prPartner').value=p.partner||'';$('prObjective').value=p.objective||'';$('prAudience').value=p.audience||'';$('prBudgetPlanned').value=p.budget_planned??'';$('prBudgetActual').value=p.budget_actual??'';$('prNextAction').value=p.next_action||'';$('prNextDue').value=p.next_action_due||'';$('prEvent').value=p.event_id||'';$('prNotes').value=p.notes||'';$('projectDeleteBtn').style.display='inline-flex';renderProjectVotePanel(id);renderProjectTasks(id);renderProjectUpdates(id);$('projectDlg').showModal()};

async function saveProject(ev){ev.preventDefault();const row={title:$('prTitle').value.trim(),summary:$('prSummary').value.trim()||null,status:$('prStatus').value,priority:$('prPriority').value,category:$('prCategory').value,owner_id:$('prOwner').value||null,start_date:$('prStart').value||null,target_date:$('prTarget').value||null,location:$('prLocation').value.trim()||null,partner:$('prPartner').value.trim()||null,objective:$('prObjective').value.trim()||null,audience:$('prAudience').value.trim()||null,budget_planned:$('prBudgetPlanned').value===''?null:Number($('prBudgetPlanned').value),budget_actual:$('prBudgetActual').value===''?null:Number($('prBudgetActual').value),next_action:$('prNextAction').value.trim()||null,next_action_due:$('prNextDue').value||null,event_id:$('prEvent').value||null,notes:$('prNotes').value.trim()||null};if(editProjectId){const {error}=await db.from('projects').update(row).eq('id',editProjectId);if(error)return toast(error.message);toast('Progetto aggiornato')}else{const {data,error}=await db.from('projects').insert({...row,created_by:app.currentUser.id}).select('id').single();if(error)return toast(error.message);editProjectId=data.id;toast('Progetto creato')}$('projectDlg').close();await loadProjects()}
async function deleteProject(){if(!editProjectId)return;const p=projects.find(x=>x.id===editProjectId);if(!confirm(`Eliminare definitivamente “${p.title}” con tutti i task e aggiornamenti?`))return;const {error}=await db.from('projects').delete().eq('id',editProjectId);if(error)return toast(error.message);$('projectDlg').close();toast('Progetto eliminato');await loadProjects()}

function renderProjectTasks(id){const ts=projectTasks(id);$('projectTasksList').innerHTML=ts.length?ts.map(t=>`<article class="project-task-item ${t.status==='blocked'?'project-blocked':''}" onclick="openProjectTask('${t.id}')"><h5>${esc(t.title)}</h5><p>${taskStatusLabels[t.status]} · ${priorityLabels[t.priority]}${t.assigned_to?' · '+esc(ownerName(t.assigned_to)):''}${t.due_date?' · '+fmtDate(t.due_date):''}</p></article>`).join(''):'<div class="project-empty">Nessun task.</div>'}
window.openProjectTask=id=>{const t=tasks.find(x=>x.id===id);if(!t)return;editTaskId=id;$('projectTaskTitle').textContent='Modifica task';$('ptTitle').value=t.title;$('ptStatus').value=t.status;$('ptPriority').value=t.priority;$('ptOwner').value=t.assigned_to||'';$('ptDue').value=t.due_date||'';$('ptNotes').value=t.notes||'';$('projectTaskDelete').style.display='inline-flex';$('projectTaskDlg').showModal()};
function newTask(){if(!editProjectId)return toast('Salva prima il progetto');editTaskId=null;$('projectTaskForm').reset();$('projectTaskTitle').textContent='Nuovo task';$('ptStatus').value='todo';$('ptPriority').value='medium';$('projectTaskDelete').style.display='none';$('projectTaskDlg').showModal()}
async function saveTask(ev){ev.preventDefault();const row={project_id:editProjectId,title:$('ptTitle').value.trim(),status:$('ptStatus').value,priority:$('ptPriority').value,assigned_to:$('ptOwner').value||null,due_date:$('ptDue').value||null,notes:$('ptNotes').value.trim()||null};if(editTaskId){const {error}=await db.from('project_tasks').update(row).eq('id',editTaskId);if(error)return toast(error.message)}else{const {error}=await db.from('project_tasks').insert({...row,created_by:app.currentUser.id});if(error)return toast(error.message)}$('projectTaskDlg').close();await loadProjects();if(editProjectId)renderProjectTasks(editProjectId)}
async function deleteTask(){if(!editTaskId)return;if(!confirm('Eliminare questo task?'))return;const {error}=await db.from('project_tasks').delete().eq('id',editTaskId);if(error)return toast(error.message);$('projectTaskDlg').close();await loadProjects();if(editProjectId)renderProjectTasks(editProjectId)}

function renderProjectUpdates(id){const uu=projectUpdates(id);$('projectUpdatesList').innerHTML=uu.length?uu.slice(0,12).map(u=>`<article class="project-update-item"><b>${u.update_type==='decision'?'Decisione':u.update_type==='milestone'?'Traguardo':u.update_type==='risk'?'Rischio':'Nota'}</b><p>${esc(u.body)}</p><small>${new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(u.created_at))}${u.created_by?' · '+esc(ownerName(u.created_by)):''}</small></article>`).join(''):'<div class="project-empty">Nessun aggiornamento.</div>'}
async function addUpdate(){if(!editProjectId)return toast('Salva prima il progetto');const body=$('projectUpdateText').value.trim();if(!body)return;const {error}=await db.from('project_updates').insert({project_id:editProjectId,body,update_type:$('projectUpdateType').value,created_by:app.currentUser.id});if(error)return toast(error.message);$('projectUpdateText').value='';await loadProjects();renderProjectUpdates(editProjectId)}

export function initProjects(){
 $('newProjectBtn').onclick=()=>{clearProjectForm();$('projectDlg').showModal()};$('projectClose').onclick=()=>$('projectDlg').close();$('projectCancel').onclick=()=>$('projectDlg').close();$('projectForm').addEventListener('submit',saveProject);$('projectDeleteBtn').onclick=deleteProject;
 document.querySelectorAll('.projects-tab').forEach(b=>b.onclick=()=>setTab(b.dataset.ptab));$('projectSearch').oninput=renderArchive;$('projectStatusFilter').onchange=renderArchive;$('projectPriorityFilter').onchange=renderArchive;
 document.querySelectorAll('.project-kpi').forEach(k=>k.onclick=()=>{setTab('archive');const f=k.dataset.filter;if(f==='idea')$('projectStatusFilter').value='idea';else if(f==='completed')$('projectStatusFilter').value='completed';else $('projectStatusFilter').value='all';renderArchive()});
 $('addProjectTask').onclick=newTask;$('projectTaskClose').onclick=()=>$('projectTaskDlg').close();$('projectTaskCancel').onclick=()=>$('projectTaskDlg').close();$('projectTaskForm').addEventListener('submit',saveTask);$('projectTaskDelete').onclick=deleteTask;$('addProjectUpdate').onclick=addUpdate;
}
